### ISSUE TITLE
[BUG] Sequences or Playlists with Spaces in Name will not trigger through HomeAssistant

### ISSUE THREAD

**Issue by GraphicHealer** [Aleks130699/ha-fpp#10]
I just tested this multiple times, anytime I have a space in the name of a sequence or playlist, it will not be triggered by this home assistant integration. It will only work when there is not a space in the name. Can this be fixed?

**Comment by GraphicHealer** [comment]
After looking at the code, I think I figured out what the problem is. You are not URL-Encoding the strings sent to the rest API commands. If you were to URL-Encode the names of the playlists, I think Falcon Player will read them properly.

**Comment by tobywhiting10** [comment]
I also have had this issue.
Work around for now was to create a playlist that doesn't have any spaces in the name and add the sequence I want to trigger in that.
