### ISSUE TITLE
Cannot start a playlist, missing stop button

### ISSUE THREAD

**Issue by madsci1016** [Aleks130699/ha-fpp#2]
Setting up a workbench environment (router, HAOS, FPP, figate, etc all VMs in a single thin client running proxmox for easy travel) for teaching at minis. Brand new HA install, newest version of this plugin installed by HACS, FPP v8.x

All statuses seem to work, Most controls seem to work. Except "starting a playlist" doesn't do anything, and there's no "stop" button when a playlist is playing. The rest seems fine. 

My home install, still on v1.0 of the repository you forked (where i fixed the few lines that prevented it from running) and FPP v7 everything still works fine, including stop buttons and starting playlists. 

Anything i can do to help track this down for you? Can't seem to see any meaningful log entries in HA and don't know how to get to logs in FPP.

**Comment by madsci1016** [comment]
Well, fixed the playlist starting issue by changing the playlist name to not have a space in it, now it plays when selected. 

Still no stop button. Only pause. would like the stop button back.

**Comment by madsci1016** [comment]
Just as a check, i can call the Media player: Stop service manually in HA and it does stop FPP. So sounds like it's just a GUI bug that we lost the stop button.

**Comment by Aleks130699** [comment]
> Just as a check, i can call the Media player: Stop service manually in HA and it does stop FPP. So sounds like it's just a GUI bug that we lost the stop button.

I'm using a mini media player card and it has a stop button,

**Comment by madsci1016** [comment]
> > Just as a check, i can call the Media player: Stop service manually in HA and it does stop FPP. So sounds like it's just a GUI bug that we lost the stop button.
> 
> I'm using a mini media player card and it has a stop button, ![image](https://private-user-images.githubusercontent.com/52662761/337875666-25a59aca-9b81-43ec-bce8-4a0739bc9445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTUxNzQsIm5iZiI6MTcxOTE1NDg3NCwicGF0aCI6Ii81MjY2Mjc2MS8zMzc4NzU2NjYtMjVhNTlhY2EtOWI4MS00M2VjLWJjZTgtNGEwNzM5YmM5NDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE1MDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTM3YTAyOGMyYjlkMjg4NGRlNDgyNTk4Zjk1N2VkZjI5OTVlMTE5OTM3YzM0NTgxZWMxNjgxMzFjYThmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qEdmwMs_Y2Oday5yxtiCq6Z6BTf6S4YIz2CRSK-kw8)

I'm using the built in media control card, and it looks like this. 

![Screenshot 2024-06-23 100242](https://github.com/Aleks130699/ha-fpp/assets/1082294/f89ca5d6-d87a-4588-83df-76ce1f665911)

I installed 'Mini media player' through hacs, also missing the stop button:
![Screenshot 2024-06-23 100847](https://github.com/Aleks130699/ha-fpp/assets/1082294/4523a768-8516-402d-b3cb-0a5d71a01f04)

I'm on V1.1.3 of your plugin.

**Comment by Aleks130699** [comment]
> > > Just as a check, i can call the Media player: Stop service manually in HA and it does stop FPP. So sounds like it's just a GUI bug that we lost the stop button.
> > 
> > 
> > I'm using a mini media player card and it has a stop button, ![image](https://private-user-images.githubusercontent.com/52662761/337875666-25a59aca-9b81-43ec-bce8-4a0739bc9445.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTUxNzQsIm5iZiI6MTcxOTE1NDg3NCwicGF0aCI6Ii81MjY2Mjc2MS8zMzc4NzU2NjYtMjVhNTlhY2EtOWI4MS00M2VjLWJjZTgtNGEwNzM5YmM5NDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE1MDExNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmZTM3YTAyOGMyYjlkMjg4NGRlNDgyNTk4Zjk1N2VkZjI5OTVlMTE5OTM3YzM0NTgxZWMxNjgxMzFjYThmNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0qEdmwMs_Y2Oday5yxtiCq6Z6BTf6S4YIz2CRSK-kw8)
> 
> I'm using the built in media control card, and it looks like this.
> 
> ![Screenshot 2024-06-23 100242](https://private-user-images.githubusercontent.com/1082294/342073949-f89ca5d6-d87a-4588-83df-76ce1f665911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTg3MTMsIm5iZiI6MTcyMjMxODQxMywicGF0aCI6Ii8xMDgyMjk0LzM0MjA3Mzk0OS1mODljYTVkNi1kODdhLTQ1ODgtODNkZi03NmNlMWY2NjU5MTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDU0NjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjUyMDAwMTRmOTA5ZWY1NDU5NTkxOTA1ZGEzYmYyMTU2MGExZTBiMzI4N2ViOWQ3ZWJhYjljNThiNmM3MmE0MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LGfZwofbNXQ8JBx4KF3CkKDM00T_FbWTRB6hQmftsv8)
> 
> I installed 'Mini media player' through hacs, also missing the stop button: ![Screenshot 2024-06-23 100847](https://private-user-images.githubusercontent.com/1082294/342074304-4523a768-8516-402d-b3cb-0a5d71a01f04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMTg3MTMsIm5iZiI6MTcyMjMxODQxMywicGF0aCI6Ii8xMDgyMjk0LzM0MjA3NDMwNC00NTIzYTc2OC04NTE2LTQwMmQtYjNjYi0wYTVkNzFhMDFmMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzBUMDU0NjUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U4MTQzMzY2YjUzNzE2YjM2MzE4MTNhNTQ2MjMwNjg1MzliNDZmNzlkODUwMDE3NzgxODllYzJlYTViMDM3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.0xaLM23O0OsUVWXO1f6Wwwi0gL63IEQW0LcMIsOMtLQ)
> 
> I'm on V1.1.3 of your plugin.

In mini-media-player, select "stop" from the "Replace Mute" option 
![image](https://github.com/user-attachments/assets/ddc8c330-8f32-44cd-afe9-30aa30106f39)
